### ISSUE TITLE
Стрелка влево для минимизации дерева не кликается

### ISSUE THREAD

**Issue by wlatt1991** [64j/MODxRE2_jquery#10]
В мозилле на mac os el capitan стрелка влево для минимизации дерева не кликается

**Comment by 64j** [comment]
на данный момент ветка MODxRE2_jquery в работе, переписывается весь JS

**Comment by wlatt1991** [comment]
Если попасть в определенные пиксели этой кнопки, то дерево сворачивается влево, но обратно уже не разворачивается. То есть при попытке развернуть стрелка переворачивается, а дерево так и остается скрытым

**Comment by Dmi3yy** [comment]
поправили можно закрывать

**Comment by 64j** [comment]
fixed

**Comment by 64j** [comment]
fixed
