### ISSUE TITLE
Контекстное меню ресурса

### ISSUE THREAD

**Issue by wlatt1991** [64j/MODxRE2_jquery#11]
Вот бы еще в контекстном меню при клике по ресурсу правой кнопкой мыши исчезала например кнопка удалить, если для менеджера запрещено удалять этот ресурс. Ну и соответственно остальные кнопки появлялись и исчезали в зависимости от прав текущего менеджера.

**Comment by 64j** [comment]
хорошо, постараемся учесть

**Comment by 64j** [comment]
fixed
