### ISSUE TITLE
Иконка настройки не исчезает при отсутствии прав на все пункты из выпадающего меню

### ISSUE THREAD

**Issue by wlatt1991** [64j/MODxRE2_jquery#12]
Иконка настройки (она справа от "просмотр") не исчезает при отсутствии прав на все пункты из выпадающего меню. Она есть, на нее наводишь и ничего не происходит, на клик тоже не реагирует, смысла оставлять её в данном случае не вижу

**Comment by 64j** [comment]
ну да, смысла нет, удалим)))

**Comment by Dmi3yy** [comment]
пофиксил

**Comment by 64j** [comment]
fixed
