### ISSUE TITLE
Не обновляется дерево после очистки корзины

### ISSUE THREAD

**Issue by wlatt1991** [64j/MODxRE2_jquery#15]
Не обновляется дерево после очистки корзины

**Comment by 64j** [comment]
Ветка MODxRE2_jquery ещё не скоро будет закончена, используйте MODxRE2_ver_2
https://github.com/64j/MODxRE2_ver_2

**Comment by Dmi3yy** [comment]
fixed

**Comment by 64j** [comment]
fixed
